Neighbourly/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views as auth_views
from django_registration.backends.one_step.views import RegistrationView
from rest_framework.authtoken.views import obtain_auth_token


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/register/',
        RegistrationView.as_view(success_url='/update-profile/'),
        name='django_registration_register'),
    path('accounts/login/', auth_views.LoginView.as_view(extra_context={'next': '/'}), name='django_registration_login'),
    path('accounts/', include('django_registration.backends.one_step.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('logout/', auth_views.LogoutView.as_view()),
    path('', include(('Posts.urls','Posts'), namespace='Posts')),
    path('api-token-auth/', obtain_auth_token, name='api_token_auth'),
]

Posts/urls.py
from . import  views
from django.urls import path

app_name = 'Posts'

urlpatterns = [
    path('',views.index,name='index'),
    path('my-profile/',views.myProfile,name='my_profile'),
    path('update-profile/',views.updateProfile,name='update_profile'),
    path('share-notice/<int:neighborhood_id>',views.shareNotice,name='share_notice'),
    path('notices/<int:neighborhood_id>',views.viewNotices,name='view_notices'),
    path('add-business/',views.addBusiness,name='add_business'),
    path('businesses/',views.business,name='view_businesses'),
    path('search-businesses/',views.searchBusiness,name='search_businesses'),
    path('health-centers/<int:neighborhood_id>',views.healthCenters,name='health_centers'),
    path('police-stations/<int:neighborhood_id>',views.policeStations,name='police_stations'),
    path('neighborhoods/',views.neighborhood,name='view_neighborhoods'),
    path('add-neighborhood/',views.addNeighborhood,name='add_neighborhood'),
    path('join-neighborhood/<int:neighborhood_id>',views.joinNeighborhood,name='join_neighborhood'),

]

Posts/models.py
from django.db import models
from django.contrib.auth.models import User
from phone_field import PhoneField
from cloudinary.models import CloudinaryField
import datetime as dt


# Create your models here.
#Neighborhood Model
class Neighborhood(models.Model):
    location = models.CharField(max_length=100)
    hood_name = models.CharField(max_length=100)
    population = models.PositiveIntegerField(null=True)
    user = models.ForeignKey(User,on_delete=models.CASCADE, default=True)
    
    
    def __str__(self):
        return str(self.hood_name)
    
    def save_neighborhood(self):
        self.save()


#User/Profile Model
class Profile(models.Model):
    prof_pic = models.ImageField(upload_to='images/',blank=True)
    bio = models.CharField(max_length = 250, null=True)
    email = models.EmailField(max_length=100)
    neighborhood = models.ForeignKey(Neighborhood,on_delete=models.CASCADE, null=True, default=2)
    user = models.OneToOneField('auth.User',on_delete=models.CASCADE)
    date_joined = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return str(self.user)
    
    def save_profile(self):
        self.save()
   
    @classmethod
    def profile(cls):
        profile = cls.objects.filter(id=Profile.id)
        return profile


#Business Model
class Business(models.Model):
    bsns_name = models.CharField(max_length=250)
    neighborhood = models.ForeignKey(Neighborhood,on_delete=models.CASCADE, null=True)
    user = models.ForeignKey(User,on_delete=models.CASCADE, null=True)
    bsns_email = models.EmailField(max_length=100)
    
    def __str__(self):
        return self.bsns_name
    
    def create_business(self):
        self.save()
    
    def delete_business(self):
        self.delete()
        
    @classmethod
    def find_business(cls,id):
        found_businesses = cls.objects.get(id = id)
        return found_businesses
    
#Notices Model
class Notice(models.Model):
    notice_title = models.CharField(max_length=100, null=True)
    notice_pic = models.ImageField(upload_to='images/',blank=True, null=True)
    notice_details=models.CharField(max_length=250, null=True)
    post_date=models.DateField(auto_now_add=True, null=True)
    user=models.ForeignKey(User,on_delete=models.CASCADE, null=True)
    neighborhood = models.ForeignKey(Neighborhood, on_delete=models.CASCADE, null=True)


    def save_notice(self):
        self.save()

    def __str__(self):
        return self.notice_title
    

#Health Centers Model
class HealthCenter(models.Model):
    hospital_name = models.CharField(max_length=100)
    email = models.EmailField(max_length=100)
    tel = PhoneField(blank=True, help_text="Hospital Phone Number")
    neighborhood = models.ForeignKey(Neighborhood, on_delete=models.CASCADE)
  
    def __str__(self):
        return str(self.hospital_name)
    
    def save_healthcenter(self):
        self.save()

#Police Dept's Model
class Police(models.Model):
    station_name = models.CharField(max_length=100)
    email = models.EmailField(max_length=100)
    tel = PhoneField(blank=True, help_text="Police Station Phone Number")
    neighborhood = models.ForeignKey(Neighborhood, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.station_name)
    
    def save_police(self):
        self.save()

Posts/forms.py
from django import forms
from .models import Neighborhood,Profile,Business,Notice,HealthCenter,Police
from cloudinary.models import CloudinaryField

class CreateHoodForm(forms.ModelForm):
    class Meta:
        model = Neighborhood
        fields=['hood_name','location','population']


class UpdateProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields=['prof_pic','bio']
        
        
class SubmitBusinessForm(forms.ModelForm):
    class Meta:
        model = Business
        fields=['bsns_name','bsns_email']
        

class ShareNoticeForm(forms.ModelForm):
    class Meta:
        model = Notice
        exclude = ['user', 'neighborhood']
        

class AddBusinessForm(forms.ModelForm):
    class Meta:
        model = Business
        exclude = ['user', 'neighborhood']
        
        
class AddNeighborhoodForm(forms.ModelForm):
    class Meta:
        model = Neighborhood
        exclude = ['user']
        
class JoinNeighborhoodForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields=['neighborhood']

Posts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from .models import Neighborhood,Profile,Business,Notice,HealthCenter,Police
from .forms import CreateHoodForm,UpdateProfileForm,SubmitBusinessForm,ShareNoticeForm,AddBusinessForm,AddNeighborhoodForm,JoinNeighborhoodForm
from .email import send_welcome_email



#landing/index page
def index(request):
    health_centers=HealthCenter.objects.all()
    police_stations=Police.objects.all()
    
    return render(request,'index.html', locals())


#profilePage
def myProfile(request):
    current_user = request.user

    if Profile.objects.filter(user=current_user).first():
        userProfile = Profile.objects.all()
        userNotices = Notice.objects.filter(user=request.user)
        notices=Notice.objects.all()
        profile = Profile.objects.filter(user=current_user).first()
    else:
        profile = Profile(user=current_user)
        profile.save()
        send_welcome_email(current_user.username, current_user.email)


    return render(request, 'posts/profile.html', locals())


#updateProfile
def updateProfile(request):
    my_prof = User.objects.get(username=request.user)
    current_user = request.user

    if request.method == 'POST':
        updateProf = UpdateProfileForm(request.POST,request.FILES)

        if updateProf.is_valid():
            updateProfile = updateProf.save(commit=False)
            updateProfile.user = request.user
            updateProf.save()
            send_welcome_email(current_user.username, current_user.email)
              
        return redirect('Posts:my_profile')
    else:
        updateProf = UpdateProfileForm()
    
    return render(request, 'posts/update_profile.html', locals())


#neighborhoods/join a neighborhood
@login_required(login_url='/accounts/login')
def neighborhood(request):
    neighborhoods=Neighborhood.objects.all()
    form = AddNeighborhoodForm()
    joinForm = JoinNeighborhoodForm()
     
    return render(request,'posts/neighborhoods.html', locals())


#add a neighborhood
def addNeighborhood (request):
    form = AddNeighborhoodForm()
    joinForm = JoinNeighborhoodForm()

    
    if request.method == 'POST':
        form = AddNeighborhoodForm(request.POST,request.FILES)
        user = request.user.id
        
        if form.is_valid():
            neighborhood = form.save(commit=False)
            neighborhood.user = request.user
            neighborhood.save()
        return redirect('Posts:view_neighborhoods')
    else:
        form = AddNeighborhoodForm()
        joinForm = JoinNeighborhoodForm(instance=request.user.profile)

        return render(request, 'posts/neighborhoods.html', locals())


#join neighborhood
def joinNeighborhood(request, neighborhood_id):
    joinForm = JoinNeighborhoodForm()
    
    if request.method == 'POST':
        joinForm = JoinNeighborhoodForm(request.POST,request.FILES, instance=request.user.profile)
        neighborhood = get_object_or_404(Neighborhood,pk=neighborhood_id)
        if joinForm.is_valid():
            new_occupant = joinForm.save(commit=False)
            new_occupant.user = request.user
            new_occupant.save()
        return redirect('Posts:view_notices', neighborhood_id)


#share a notice
@login_required(login_url='/accounts/login')
def shareNotice(request, neighborhood_id):
    form = ShareNoticeForm()
    
    if request.method == 'POST':
        form = ShareNoticeForm(request.POST,request.FILES)
        user = request.user.id
        
        if form.is_valid():
            announcement = form.save(commit=False)
            announcement.user = request.user
            announcement.save()

        return redirect('Posts:view_notices', neighborhood_id)
    else:
        form = ShareNoticeForm()
        return render(request, 'posts/share_notice.html', locals())
    

#view notices/alerts/announcements
@login_required(login_url='/accounts/login')
def viewNotices(request, neighborhood_id):
    notices=Notice.objects.all()
    neighborhood = get_object_or_404(Neighborhood,pk=neighborhood_id)
    neighborhoodNotices = Notice.objects.filter(neighborhood=neighborhood)
    print(notices, "=====ALL NOTICES======")
    print(notices, "======RESPECTIVE HOOD NOTICES=====")

    return render(request,'posts/notices.html', locals())


#view businesses
@login_required(login_url='/accounts/login')
def business(request):
    businesses=Business.objects.all()
    form = AddBusinessForm()
    
    return render(request,'posts/businesses.html', locals())


#add a business
def addBusiness (request):
    form = AddBusinessForm()
    
    if request.method == 'POST':
        form = AddBusinessForm(request.POST,request.FILES)
        user = request.user.id
        
        if form.is_valid():
            business = form.save(commit=False)
            business.user = request.user
            business.save()
        return redirect('Posts:view_businesses')
    else:
        form = AddBusinessForm()
        return render(request, 'posts/businesses.html', locals())

#search businesses
@login_required(login_url='/accounts/login')
def searchBusiness(request):

    if 'search' in request.GET and request.GET["search"]:
    
        search_term = request.GET.get("search")
        searched_businesses = Business.objects.filter(bsns_name__icontains=search_term)
        message = f"{search_term}"
        
        return render(request, 'posts/search_results.html', locals())
    
    else:
        
        message = "you haven't searched for any business"  
        return render(request, 'posts/search_results.html', locals())
    

#view health centers
def healthCenters(request, neighborhood_id):
    neighborhood = get_object_or_404(Neighborhood,pk=neighborhood_id)
    health_centers = HealthCenter.objects.filter(neighborhood=neighborhood)
    
    return render(request,'posts/health_centers.html', locals())


#view police stations
def policeStations(request, neighborhood_id):
    neighborhood = get_object_or_404(Neighborhood,pk=neighborhood_id)
    police_stations = Police.objects.filter(neighborhood=neighborhood)
    
    return render(request,'posts/police_stations.html', locals())

Posts/templates/index.html
{% extends 'posts/base.html'%} {% load bootstrap4 %} {% block content %} {{ block.super }}

<div class="container-fluid topBuffer">
    <div class="jumbotron bg-img">
        <div class="row justify-content-around">

            <!-- ============== start of about div ================== -->

            <div class="col-xs-6 col-sm-7 col-md-7 col-lg-7">

                <div class="card border-info slightOpaicty mb-3">
                    <div class="card-header">Neighbourly </div>
                    <div class="card-body">
                        <h5 class="card-title">About us</h5>
                        <p class="card-text"> Neighbourly enables our users to be kept in the loop about everything helpful that is happening in their neighborhood. From contact information of different handypersons to meeting-announcements or even alerts.</p>
                    </div>
                </div>
            </div>

            <!-- ============== end of about div ================== -->


            <!-- ============== start of resources-links div ================== -->
            <div class="col-xs-6 col-sm-5 col-md-5 col-lg-5">
                <div class="card border-info slightOpaicty">
                    <div class="card-header"> Helpful Resources </div>
                    <ul class="list-group text-info list-group-flush">
                        <li class="list-group-item"><a href="/neighborhoods"> Join a Neighborhood</a></li>

                        {% if request.user.profile.neighborhood %}
                        <li class="list-group-item"><a href="{% url 'Posts:view_notices' request.user.profile.neighborhood.id %}">View Neighborhood Notices</a></li>
                        {% endif %}

                        <li class="list-group-item"><a href="/businesses">View all Neighborhoods' Businesses</a></li>
                    </ul>
                </div>
            </div>
            <!-- ============== end of resources-links div ================== -->

        </div>

        <!-- jumbotron ends here -->
    </div>
    <!-- container ends here -->
    <div class="col-md-12">
        <div class=" footer text-center ">
            <ul id="footer1 ">
                <li><a href="admin "> ADMIN </a> </li>
                <li><a href="# ">ABOUT US</a> </li>
                <li><a href="# ">SUPPORT</a></li>
                <li><a href="# ">PRESS</a></li>
                <li><a href="# ">API</a></li>
                <li><a href="# ">JOBS</a></li>
                <li><a href="# ">PRIVACY</a></li>
                <li><a href="# ">TERMS</a></li>
                <li><a href="# ">DIRECTORY</a></li>
                <li><a href="# ">COMMUNITY RULES </a></li>
                <br>
                <li style="font-size:10px; "> <strong>© 2020 ROSE KAIRU</strong></li>
            </ul>
        </div>
    </div>
</div>

{% endblock %}

Posts/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-dark">
    <a class="navbar-brand" href="/"> <img src="/static/images/nav.jpg" style="width:25vh; height:10vh;" alt="logo"> | </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="/" style="color: whitesmoke;"> Neighbourly <span class="sr-only">(current)</span></a>
            </li>
        </ul>

        <form action="{% url 'Posts:search_businesses' %}" class="form-inline my-2 my-lg-0">
            <input class="form-control form-control-sm mr-sm-2" name="search" type="search" placeholder="Search for Businesses... &#xF002;" style="font-family:Arial, FontAwesome" aria-label="Search">
        </form>


        <ul class="navbar-nav ml-auto">


            {% if user.is_authenticated %}

            <li class="nav-item">
                <a class="nav-link" href="/my-profile" style="color: gold;"> {{request.user.username}} <i class="fa fa-user-circle-o" style="font-size:20px"></i> </a>
            </li>
            {% else %}
            <li class="nav-item">
                <a class="nav-link" href="/accounts/login" style="color: goldenrod;">Register/Login | </a>
            </li>
            {% endif %}
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="color: chartreuse;">
            Resources
          </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="/businesses">Businesses</a>
                    <div class="dropdown-divider"></div>
                    {%if request.user.profile.neighborhood%}
                    <a class="dropdown-item" href="{% url 'Posts:health_centers' request.user.profile.neighborhood.id%}">Health Centers</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="{% url 'Posts:police_stations' request.user.profile.neighborhood.id %}">Police Contacts</a> {%endif%}
                </div>
            </li>

            {% if user.is_authenticated %}

            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown2" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="color: yellowgreen;">
                NoticeBoard
              </a>

                <div class="dropdown-menu" aria-labelledby="navbarDropdown2">
                    {% if request.user.profile.neighborhood %}

                    <a class="dropdown-item" href="{% url 'Posts:view_notices' request.user.profile.neighborhood.id%}">View Notices</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="{% url 'Posts:share_notice' request.user.profile.neighborhood.id%}">Share Notice</a> {% endif %}
                </div>
            </li>

            <li>
                <a class="nav-link" href="/logout"> | <i class="fa fa-sign-out" style="font-size:20px;color: whitesmoke;" ></i> </i></a>
            </li>

            {% endif %}

        </ul>

    </div>
</nav>