Neighbourly/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views as auth_views
from django_registration.backends.one_step.views import RegistrationView
from rest_framework.authtoken.views import obtain_auth_token


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/register/',
        RegistrationView.as_view(success_url='/update-profile/'),
        name='django_registration_register'),
    path('accounts/login/', auth_views.LoginView.as_view(extra_context={'next': '/'}), name='django_registration_login'),
    path('accounts/', include('django_registration.backends.one_step.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('logout/', auth_views.LogoutView.as_view()),
    path('', include(('Posts.urls','Posts'), namespace='Posts')),
    path('api-token-auth/', obtain_auth_token, name='api_token_auth'),
]

Posts/urls.py
from . import  views
from django.urls import path

app_name = 'Posts'

urlpatterns = [
    path('',views.index,name='index'),
    path('my-profile/',views.myProfile,name='my_profile'),
    path('update-profile/',views.updateProfile,name='update_profile'),
    path('share-notice/<int:neighborhood_id>',views.shareNotice,name='share_notice'),
    path('notices/<int:neighborhood_id>',views.viewNotices,name='view_notices'),
    path('add-business/',views.addBusiness,name='add_business'),
    path('businesses/',views.business,name='view_businesses'),
    path('search-businesses/',views.searchBusiness,name='search_businesses'),
    path('health-centers/<int:neighborhood_id>',views.healthCenters,name='health_centers'),
    path('police-stations/<int:neighborhood_id>',views.policeStations,name='police_stations'),
    path('neighborhoods/',views.neighborhood,name='view_neighborhoods'),
    path('add-neighborhood/',views.addNeighborhood,name='add_neighborhood'),
    path('join-neighborhood/<int:neighborhood_id>',views.joinNeighborhood,name='join_neighborhood'),

]

Posts/models.py
from django.db import models
from django.contrib.auth.models import User
from phone_field import PhoneField
from cloudinary.models import CloudinaryField
import datetime as dt


# Create your models here.
#Neighborhood Model
class Neighborhood(models.Model):
    location = models.CharField(max_length=100)
    hood_name = models.CharField(max_length=100)
    population = models.PositiveIntegerField(null=True)
    user = models.ForeignKey(User,on_delete=models.CASCADE, default=True)
    
    
    def __str__(self):
        return str(self.hood_name)
    
    def save_neighborhood(self):
        self.save()


#User/Profile Model
class Profile(models.Model):
    prof_pic = models.ImageField(upload_to='images/',blank=True)
    bio = models.CharField(max_length = 250, null=True)
    email = models.EmailField(max_length=100)
    neighborhood = models.ForeignKey(Neighborhood,on_delete=models.CASCADE, null=True, default=2)
    user = models.OneToOneField('auth.User',on_delete=models.CASCADE)
    date_joined = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return str(self.user)
    
    def save_profile(self):
        self.save()
   
    @classmethod
    def profile(cls):
        profile = cls.objects.filter(id=Profile.id)
        return profile


#Business Model
class Business(models.Model):
    bsns_name = models.CharField(max_length=250)
    neighborhood = models.ForeignKey(Neighborhood,on_delete=models.CASCADE, null=True)
    user = models.ForeignKey(User,on_delete=models.CASCADE, null=True)
    bsns_email = models.EmailField(max_length=100)
    
    def __str__(self):
        return self.bsns_name
    
    def create_business(self):
        self.save()
    
    def delete_business(self):
        self.delete()
        
    @classmethod
    def find_business(cls,id):
        found_businesses = cls.objects.get(id = id)
        return found_businesses
    
#Notices Model
class Notice(models.Model):
    notice_title = models.CharField(max_length=100, null=True)
    notice_pic = models.ImageField(upload_to='images/',blank=True, null=True)
    notice_details=models.CharField(max_length=250, null=True)
    post_date=models.DateField(auto_now_add=True, null=True)
    user=models.ForeignKey(User,on_delete=models.CASCADE, null=True)
    neighborhood = models.ForeignKey(Neighborhood, on_delete=models.CASCADE, null=True)


    def save_notice(self):
        self.save()

    def __str__(self):
        return self.notice_title
    

#Health Centers Model
class HealthCenter(models.Model):
    hospital_name = models.CharField(max_length=100)
    email = models.EmailField(max_length=100)
    tel = PhoneField(blank=True, help_text="Hospital Phone Number")
    neighborhood = models.ForeignKey(Neighborhood, on_delete=models.CASCADE)
  
    def __str__(self):
        return str(self.hospital_name)
    
    def save_healthcenter(self):
        self.save()

#Police Dept's Model
class Police(models.Model):
    station_name = models.CharField(max_length=100)
    email = models.EmailField(max_length=100)
    tel = PhoneField(blank=True, help_text="Police Station Phone Number")
    neighborhood = models.ForeignKey(Neighborhood, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.station_name)
    
    def save_police(self):
        self.save()

Posts/forms.py
from django import forms
from .models import Neighborhood,Profile,Business,Notice,HealthCenter,Police
from cloudinary.models import CloudinaryField

class CreateHoodForm(forms.ModelForm):
    class Meta:
        model = Neighborhood
        fields=['hood_name','location','population']


class UpdateProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields=['prof_pic','bio']
        
        
class SubmitBusinessForm(forms.ModelForm):
    class Meta:
        model = Business
        fields=['bsns_name','bsns_email']
        

class ShareNoticeForm(forms.ModelForm):
    class Meta:
        model = Notice
        exclude = ['user', 'neighborhood']
        

class AddBusinessForm(forms.ModelForm):
    class Meta:
        model = Business
        exclude = ['user', 'neighborhood']
        
        
class AddNeighborhoodForm(forms.ModelForm):
    class Meta:
        model = Neighborhood
        exclude = ['user']
        
class JoinNeighborhoodForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields=['neighborhood']

Posts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from .models import Neighborhood,Profile,Business,Notice,HealthCenter,Police
from .forms import CreateHoodForm,UpdateProfileForm,SubmitBusinessForm,ShareNoticeForm,AddBusinessForm,AddNeighborhoodForm,JoinNeighborhoodForm
from .email import send_welcome_email



#landing/index page
def index(request):
    health_centers=HealthCenter.objects.all()
    police_stations=Police.objects.all()
    
    return render(request,'index.html', locals())


#profilePage
def myProfile(request):
    current_user = request.user

    if Profile.objects.filter(user=current_user).first():
        userProfile = Profile.objects.all()
        userNotices = Notice.objects.filter(user=request.user)
        notices=Notice.objects.all()
        profile = Profile.objects.filter(user=current_user).first()
    else:
        profile = Profile(user=current_user)
        profile.save()
        send_welcome_email(current_user.username, current_user.email)


    return render(request, 'posts/profile.html', locals())


#updateProfile
def updateProfile(request):
    my_prof = User.objects.get(username=request.user)
    current_user = request.user

    if request.method == 'POST':
        updateProf = UpdateProfileForm(request.POST,request.FILES)

        if updateProf.is_valid():
            updateProfile = updateProf.save(commit=False)
            updateProfile.user = request.user
            updateProf.save()
            send_welcome_email(current_user.username, current_user.email)
              
        return redirect('Posts:my_profile')
    else:
        updateProf = UpdateProfileForm()
    
    return render(request, 'posts/update_profile.html', locals())


#neighborhoods/join a neighborhood
@login_required(login_url='/accounts/login')
def neighborhood(request):
    neighborhoods=Neighborhood.objects.all()
    form = AddNeighborhoodForm()
    joinForm = JoinNeighborhoodForm()
     
    return render(request,'posts/neighborhoods.html', locals())


#add a neighborhood
def addNeighborhood (request):
    form = AddNeighborhoodForm()
    joinForm = JoinNeighborhoodForm()

    
    if request.method == 'POST':
        form = AddNeighborhoodForm(request.POST,request.FILES)
        user = request.user.id
        
        if form.is_valid():
            neighborhood = form.save(commit=False)
            neighborhood.user = request.user
            neighborhood.save()
        return redirect('Posts:view_neighborhoods')
    else:
        form = AddNeighborhoodForm()
        joinForm = JoinNeighborhoodForm(instance=request.user.profile)

        return render(request, 'posts/neighborhoods.html', locals())


#join neighborhood
def joinNeighborhood(request, neighborhood_id):
    joinForm = JoinNeighborhoodForm()
    
    if request.method == 'POST':
        joinForm = JoinNeighborhoodForm(request.POST,request.FILES, instance=request.user.profile)
        neighborhood = get_object_or_404(Neighborhood,pk=neighborhood_id)
        if joinForm.is_valid():
            new_occupant = joinForm.save(commit=False)
            new_occupant.user = request.user
            new_occupant.save()
        return redirect('Posts:view_notices', neighborhood_id)


#share a notice
@login_required(login_url='/accounts/login')
def shareNotice(request, neighborhood_id):
    form = ShareNoticeForm()
    
    if request.method == 'POST':
        form = ShareNoticeForm(request.POST,request.FILES)
        user = request.user.id
        
        if form.is_valid():
            announcement = form.save(commit=False)
            announcement.user = request.user
            announcement.save()

        return redirect('Posts:view_notices', neighborhood_id)
    else:
        form = ShareNoticeForm()
        return render(request, 'posts/share_notice.html', locals())
    

#view notices/alerts/announcements
@login_required(login_url='/accounts/login')
def viewNotices(request, neighborhood_id):
    notices=Notice.objects.all()
    neighborhood = get_object_or_404(Neighborhood,pk=neighborhood_id)
    neighborhoodNotices = Notice.objects.filter(neighborhood=neighborhood)
    print(notices, "=====ALL NOTICES======")
    print(notices, "======RESPECTIVE HOOD NOTICES=====")

    return render(request,'posts/notices.html', locals())


#view businesses
@login_required(login_url='/accounts/login')
def business(request):
    businesses=Business.objects.all()
    form = AddBusinessForm()
    
    return render(request,'posts/businesses.html', locals())


#add a business
def addBusiness (request):
    form = AddBusinessForm()
    
    if request.method == 'POST':
        form = AddBusinessForm(request.POST,request.FILES)
        user = request.user.id
        
        if form.is_valid():
            business = form.save(commit=False)
            business.user = request.user
            business.save()
        return redirect('Posts:view_businesses')
    else:
        form = AddBusinessForm()
        return render(request, 'posts/businesses.html', locals())

#search businesses
@login_required(login_url='/accounts/login')
def searchBusiness(request):

    if 'search' in request.GET and request.GET["search"]:
    
        search_term = request.GET.get("search")
        searched_businesses = Business.objects.filter(bsns_name__icontains=search_term)
        message = f"{search_term}"
        
        return render(request, 'posts/search_results.html', locals())
    
    else:
        
        message = "you haven't searched for any business"  
        return render(request, 'posts/search_results.html', locals())
    

#view health centers
def healthCenters(request, neighborhood_id):
    neighborhood = get_object_or_404(Neighborhood,pk=neighborhood_id)
    health_centers = HealthCenter.objects.filter(neighborhood=neighborhood)
    
    return render(request,'posts/health_centers.html', locals())


#view police stations
def policeStations(request, neighborhood_id):
    neighborhood = get_object_or_404(Neighborhood,pk=neighborhood_id)
    police_stations = Police.objects.filter(neighborhood=neighborhood)
    
    return render(request,'posts/police_stations.html', locals())

Posts/templates/posts/base.html
{% load bootstrap4 %} {% load static %}

<!DOCTYPE html>
<html>

<head>
    <meta charset='utf-8'>
    <meta name='viewport' content='width=device-width, initial-scale=1'>

    <title>Neighbourly</title>
    {{ updateProf.media }} {{form.media}} {{ joinForm.media }} {% block styles %} {% bootstrap_css %}

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

    <link rel="stylesheet" href="{% static 'css/custom.css'%}"> {% endblock %}

</head>

<body>
    {% include 'navbar.html'%} {% block content %} {% endblock %} {% block scripts %}
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>


    {% bootstrap_javascript %} {% endblock %}

</body>

</html>

Posts/templates/posts/businesses.html
{% extends 'posts/base.html'%} {% load bootstrap4 %} {% block content %} {{ block.super }}

<div class="container-fluid topBuffer">
    <div class="jumbotron bg-img">
        <div class="row">

            {% if businesses %} {% for business in businesses %}
            <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3 mb-3">
                <div class="card border-info slightOpaicty">
                    <div class="card-header"> {{ business.bsns_name }} </div>
                    <ul class="list-group text-info list-group-flush">
                        <li class="list-group-item"> Hood: {{ request.user.profile.neighborhood }} </li>
                        <li class="list-group-item"> Business Email: {{ business.bsns_email }} </li>
                        <li class="list-group-item"> Contact Person: {{ business.user }} </li>
                    </ul>
                </div>
            </div>

            {% endfor %} {% else %}

            <div class="col-xs-7 col-sm-7 col-md-7 col-lg-7">
                <div class="card border-info slightOpaicty">
                    <div class="card-body"> No businesses posted yet </div>
                </div>
            </div>

            {% endif %}


            <!-- SHARE NOTICE UPLOAD FORM -->
            <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3 border border-info rounded" style="background-color:#fff;">
                <h5 class="bg-light text-dark"> Register your business here</h5>
                <form enctype="multipart/form" action="{% url 'Posts:add_business' %}" method="post">

                    {% csrf_token %} {% bootstrap_form form layout='inline' %}

                    <div class="form-group">

                        <input type="submit" class="btn btn-primary btn-sm my-2" value="Submit">
                    </div>
                </form>
            </div>

        </div>

    </div>

</div>

{% endblock %}

Posts/templates/posts/health_centers.html
{% extends 'posts/base.html'%} {% load bootstrap4 %} {% block content %} {{ block.super }}

<div class="container-fluid topBuffer">
    <h3 class="text-center"> {{ request.user.profile.neighborhood }} Health Center Contacts </h3>

    <div class="jumbotron bg-img">
        <div class="row">

            {% if health_centers %} {% for health_center in health_centers %}
            <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3">
                <div class="card border-info slightOpaicty">
                    <div class="card-header"> {{ health_center.hospital_name }} </div>
                    <ul class="list-group text-info list-group-flush">
                        <li class="list-group-item"> Neighborhood: {{ health_center.neighborhood }} </li>
                        <li class="list-group-item"> Email: {{ health_center.email }} </li>
                        <li class="list-group-item"> Tel: {{ health_center.tel }} </li>
                    </ul>
                </div>
            </div>

            {% endfor %} {% else %}
            <div class="col-xs-7 col-sm-7 col-md-7 col-lg-7 text-center align-items-center mx-auto">
                <div class="card border-info slightOpaicty">
                    <div class="card-body"> No health center contacts posted yet for {{ request.user.profile.neighborhood }} </div>
                </div>
            </div>

            {% endif %}

        </div>

    </div>

</div>

{% endblock %}

Posts/templates/posts/neighborhoods.html
{% extends 'posts/base.html'%} {% load bootstrap4 %} {% block content %} {{ block.super }}

<div class="container-fluid topBuffer">
    <div class="row">
        <div style="display:flex; align-items:baseline;">
            <h5 class="mr-2"> Select a neighborhood to join: </h5>
            <form enctype="multipart/form" action="{% url 'Posts:join_neighborhood' request.user.profile.neighborhood.id %}" method="post" style="display:flex; align-items:baseline;">
                {% csrf_token %} {% bootstrap_form joinForm layout='inline' %}

                <div class="form-group">
                    <input type="submit" class="form-control btn btn-primary btn-sm ml-2 my-2" value="Join Neighborhood">
                </div>
            </form>
        </div>
    </div>
    <div class="jumbotron bg-img">

        <div class="row">

            {% for neighborhood in neighborhoods %}
            <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3 mb-3">
                <div class="card border-info slightOpaicty">
                    <div class="card-header"> {{ neighborhood.location }} </div>
                    <ul class="list-group text-info list-group-flush">
                        <li class="list-group-item"> Hood: {{ neighborhood.hood_name }} </li>
                        <li class="list-group-item"> Population: {{ neighborhood.population }} </li>
                        <li class="list-group-item"> Admin: {{ neighborhood.user }} </li>
                    </ul>
                </div>
            </div>

            {% endfor %}


            <!-- ADD NEIGHBORHOOD FORM -->
            <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3 border border-info rounded" style="background-color:#fff;">
                <h5 class="bg-light text-dark"> Add a Neighborhood...</h5>
                <form enctype="multipart/form" action="{% url 'Posts:add_neighborhood' %}" method="post">

                    {% csrf_token %} {% bootstrap_form form layout='inline' %}

                    <div class="form-group">

                        <input type="submit" class="btn btn-primary btn-sm my-2" value="Submit">
                    </div>
                </form>
            </div>
            <!-- END OF FORM -->


        </div>
        <!-- end of row -->
    </div>
    <!-- jumbotron ends here -->
</div>
<!-- container ends here -->

{% endblock %}

Posts/templates/posts/notices.html
{% extends 'posts/base.html'%} {% load bootstrap4 %} {% block content %} {{ block.super }}

<div class="container-fluid topBuffer">
    <h3 class="text-center"> {{ request.user.profile.neighborhood }} Notices </h3>
    <hr>
    <div class="jumbotron" style="background-color:#fff;">
        <div class="row">

            <!-- ============== start of notices div ================== -->
            {% if neighborhoodNotices %} {% for notice in neighborhoodNotices %}

            <div class="col-xs-6 col-sm-7 col-md-7 col-lg-7">

                <div class="card border-info slightOpaicty mb-3">
                    <div class="card-header"> {{ notice.notice_title }} </div>

                    <div class="card-body row">

                        <div class="col-sm-5">
                            <img class="card-img-top" src="{{ notice.notice_pic.cdn_url }}" alt="Notice Image" style="max-height:250px; max-width:250px;">
                        </div>
                        <div class="col-sm-7 align-self-center">
                            <p class="card-text"> {{ notice.notice_details }} </p>
                            <p class="card-text"> Posted on: {{ notice.post_date }} <br> by: {{ notice.user }} </p>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %} {% else %}

            <div class="col-xs-6 col-sm-7 col-md-7 col-lg-7 text-center">
                <div class="card border-info slightOpaicty">
                    <div class="card-body"> No alerts/announcements posted yet for {{ request.user.profile.neighborhood }} </div>
                </div>
            </div>

            {% endif %}

            <!-- ============== end of notices div ================== -->


            <!-- ============== start of resources-links div ================== -->
            <div class="col-xs-6 col-sm-5 col-md-5 col-lg-5 scrollResources">
                <div class="card border-info slightOpaicty">
                    <div class="card-header"> Helpful Resources </div>
                    <ul class="list-group text-info list-group-flush">
                        <li class="list-group-item"> <a href="/businesses"> Businesses </a> </li>

                        {% if request.user.profile.neighborhood %}
                        <li class="list-group-item"> <a href="{% url 'Posts:health_centers' request.user.profile.neighborhood.id%}"> Health Centers </a> </li>
                        <li class="list-group-item"> <a href="{% url 'Posts:police_stations' request.user.profile.neighborhood.id %}"> Authorities: Police Contacts </a> </li>
                        {% endif %}
                    </ul>
                </div>
            </div>

            <!-- ============== end of resources-links div ================== -->

        </div>

    </div>

</div>

{% endblock %}

Posts/templates/posts/police_stations.html
{% extends 'posts/base.html'%} {% load bootstrap4 %} {% block content %} {{ block.super }}

<div class="container-fluid topBuffer">
    <h3 class="text-center"> {{ request.user.profile.neighborhood }} Police Department Contacts </h3>

    <div class="jumbotron bg-img">
        <div class="row">

            {% if police_stations %} {% for police_station in police_stations %}
            <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3">
                <div class="card border-info slightOpaicty">
                    <div class="card-header"> {{ police_station.station_name }} </div>
                    <ul class="list-group text-info list-group-flush">
                        <li class="list-group-item"> Neighborhood: {{ police_station.neighborhood }} </li>
                        <li class="list-group-item"> Email: {{ police_station.email }} </li>
                        <li class="list-group-item"> Tel: {{ police_station.tel }} </li>
                    </ul>
                </div>
            </div>

            {% endfor %} {% else %}
            <div class="col-xs-7 col-sm-7 col-md-7 col-lg-7 text-center align-items-center mx-auto">
                <div class="card border-info slightOpaicty">
                    <div class="card-body"> No police contacts posted yet for {{ request.user.profile.neighborhood }} </div>
                </div>
            </div>

            {% endif %}

        </div>

    </div>

</div>

{% endblock %}

Posts/templates/posts/profile.html
{% extends 'posts/base.html'%} {% load bootstrap4 %} {% load static %} {% block content %}

<div class="container topBuffer">
    <div class="row">

        <!-- profile card div -->
        <div class="col-xs-4 col-sm-5 col-md-5 col-lg-4 scrollBioData">
            <div class="card align-items-center text-center">

                {% if user.profile.prof_pic %}

                <img class="card-img-top rounded-circle avatar" src="{{ request.user.profile.prof_pic}}" alt="Card image" style="width:200px; height:200px;"> {% else %}
                <img class="card-img-top rounded-circle avatar" src="/static/images/nav.jpg" alt="Card image" style="width:200px; height:200px;"> {% endif %}

                <div class="card-body">
                    <h4 class="card-title"> {{ request.user.username }}</h4>
                    <p class="card-text"> Bio: {{ request.user.profile.bio }}</p>
                    <p class="card-text"> Email: {{ request.user.email }}</p>
                    <p class="card-text"> Current Location: {{ request.user.profile.neighborhood }}</p>
                    <a href="/update-profile"> Edit Profile </a>
                </div>
            </div>
        </div>
        <!-- end of profile card div-->

        <!-- user posts/posted notices div-->
        {% if userNotices %}
        <div class="col-xs-8 col-sm-7 col-md-7 col-lg-8 ml-auto">

            <h4>Notices I have shared</h4>
            {% for notice in userNotices %}

            <div class="card border-info slightOpaicty mb-3">
                <div class="card-header"> {{ notice.notice_title }} </div>

                <div class="card-body row">

                    <div class="col-sm-5">
                        <img class="card-img-top" src="{{ notice.notice_pic.cdn_url }}" alt="Notice Image" style="max-height:250px; max-width:250px;">
                    </div>
                    <div class="col-sm-7 align-self-center">
                        <p class="card-text"> {{ notice.notice_details }} </p>
                        <p class="card-text"> Posted on: {{ notice.post_date }} <br> by: {{ notice.user }} </p>
                    </div>
                </div>
            </div>
            {% endfor %}

        </div>

        {% else %}
        <div class="col-xs-8 col-sm-7 col-md-7 col-lg-8 align-self-center ml-auto">
            <div class="card border-info slightOpaicty">
                <div class="card-body"> You haven't posted any notices/alerts/announcements yet </div>
            </div>
        </div>
        {% endif %}

    </div>

</div>

{% endblock %}

Posts/templates/posts/search_results.html
{% extends 'posts/base.html' %} {% load bootstrap4 %} {% load static %} {% block content %}

<div class="container">
    <div class="row searchResults">

        {% if searched_businesses %}
        <h2>Found {{ searched_businesses |length }} businesse(s) with regards to {{message}}</h2>
        {% else %}
        <h2> Found 0 business(s) concerning {{message}}</h2>
        {% endif %}

    </div>

    <!-- business search results -->
    <div class="row">
        {% for business in searched_businesses %}

        <div class="col-xs-6 col-sm-5 col-md-5 col-lg-5">
            <div class="card border-info slightOpaicty">
                <div class="card-header"> {{ business.bsns_name }} </div>
                <ul class="list-group text-info list-group-flush">
                    <li class="list-group-item"> Hood: {{ business.neighborhood }} </li>
                    <li class="list-group-item"> Business Email: {{ business.bsns_email }} </li>
                    <li class="list-group-item"> Contact Person: {{ business.user }} </li>
                </ul>
            </div>
        </div>
        {% endfor %}
    </div>

</div>

{% endblock %}

Posts/templates/posts/share_notice.html
 {% extends 'posts/base.html' %} {% load bootstrap4 %} {% load static %} {% block content %} {{block.super}}

<div class="container-fluid topBuffer">

    <div class="jumbotron bg-img">

        <div class="row justify-content-center">
            <div class="col-lg-7 col-md-7 col-sm-7 col-xs-7">

                <!-- SHARE NOTICE UPLOAD FORM -->
                <form enctype="multipart/form" action="{% url 'Posts:share_notice' request.user.profile.neighborhood.id %}" method="post">

                    {% csrf_token %} {% bootstrap_form form layout='inline' %}

                    <div class="form-group">

                        <input type="submit" class="btn btn-primary btn-sm my-2" value="Submit">
                    </div>
                </form>
                <!-- END OF FORM -->

            </div>
        </div>

    </div>

</div>

{% endblock %}

Posts/templates/posts/update_profile.html
{% extends 'posts/base.html'%} {% load bootstrap4 %} {% load static %} {% block content %}

<div class="container-fluid topBuffer">
    <div class="jumbotron">
        <div class="row justify-content-center">
            <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3">
                <!--prof-pic column-->
                {% if user.profile.prof_pic %}
                <img class="card-img-top rounded-circle avatar" src="{{ request.user.pofile.prof_pic}}" alt="Card image" style="width:200px; height:200px;"> {% else %}
                <img class="card-img-top rounded-circle avatar" src="/static/images/nav.jpg" alt="Card image" style="width:200px; height:200px;"> {% endif %}
            </div>
            <!--end of prof pic columnn-->

            <div class="col-xs-7 col-sm-7 col-md-7 col-lg-7">
                <!-- PROFILE UPDATE FORM -->
                <form enctype="multipart/form" action="{% url 'Posts:update_profile' %}" method="post">

                    {% csrf_token %} {% bootstrap_form updateProf %}

                    <div class="form-group">

                        <input type="submit" class="btn btn-primary my-2" value="Submit">
                    </div>
                </form>

            </div>

        </div>

    </div>

</div>

{% endblock %}